[kp6]  * disable unsecure code by setting env KP6_DISABLE_UNSECURE_CODE  * Num datatype added (correctly done? please review)  * more tests for grep  * MOP.pm: more dynamic require of runtime classes and error handling.    - This solves some annoying self referential issues when a Perl6      file compiled but the resulting Perl5 code failed so that not      even MOP could be loaded when we correct that issue.  * Makefile enhancements:     - now stop on compile errors instead of creating empty files,       which broke successive compile runs     - test targets for just subsections: test_(io|math|base)     - make test now depend on make all
git-svn-id: http://svn.pugscode.org/pugs@17552 c213334d-75ef-0310-aa23-eaa082d1ae64

diff --git a/v6/v6-KindaPerl6/Makefile b/v6/v6-KindaPerl6/Makefile
--- a/v6/v6-KindaPerl6/Makefile
+++ b/v6/v6-KindaPerl6/Makefile
@@ -1,14 +1,32 @@
-OBJ = $(patsubst lib/%,lib5/%,$(wildcard lib/KindaPerl6/Grammar/*.pm lib/KindaPerl6/Grammar.pm lib/KindaPerl6/Traverse.pm lib/KindaPerl6/Ast.pm lib/KindaPerl6/Visitor/*.pm lib/KindaPerl6/Runtime/Perl5/*.pm lib/KindaPerl6/Runtime/Perl6/*.pm ))
+OBJ = $(patsubst lib/%,lib5/%,$(wildcard lib/KindaPerl6/Grammar/*.pm lib/KindaPerl6/Grammar.pm lib/KindaPerl6/Traverse.pm lib/KindaPerl6/Ast.pm lib/KindaPerl6/Visitor/*.pm lib/KindaPerl6/Runtime/Perl5/*.pm lib/KindaPerl6/Runtime/Perl6/*.pm lib/KindaPerl6/Test/*.pm ))
+
 all: $(OBJ)
 
 lib5/KindaPerl6/Runtime/Perl6/%.pm: lib/KindaPerl6/Runtime/Perl6/%.pm
-	perl kp6-perl5.pl < $< | perltidy > temp.pm ; cp temp.pm $@
+	@echo COMPILE $< $@
+	@perl kp6-perl5.pl < $< | perltidy > temp.pm ; \
+		res=$$? ; \
+		if [ $$res = 0 -a -s temp.pm ] ; then \
+			cp temp.pm $@ ; \
+		else \
+			echo "*** Compilation failed with exit code: $$res!" ; \
+			exit; \
+		fi
 lib5/KindaPerl6/Runtime/Perl5/%.pm: lib/KindaPerl6/Runtime/Perl5/%.pm
 	cp $< $@
 lib5/%.pm: lib/%.pm
 	perl mp6.pl < $< > $@
-test:
+test: all
 	perl run_tests.pl
+
+test_io: all
+	perl run_tests.pl --section=io
+
+test_math: all
+	perl run_tests.pl --section=math
+
+test_base: all
+	perl run_tests.pl --section=''
 
 clean: 
 	rm -f $(OBJ)
