[kp6] starting to change calling convention from kp6-mp6 to kp6-kp6 in kp6-kp6 (yes, thats bootstrapping)
git-svn-id: http://svn.pugscode.org/pugs@17647 c213334d-75ef-0310-aa23-eaa082d1ae64

diff --git a/v6/v6-KindaPerl6/Makefile b/v6/v6-KindaPerl6/Makefile
--- a/v6/v6-KindaPerl6/Makefile
+++ b/v6/v6-KindaPerl6/Makefile
@@ -2,7 +2,7 @@ kp6_mp6_OBJ = $(patsubst lib-kp6-mp6/%,lib-kp6-mp6-p5/%,$(wildcard lib-kp6-mp6/K
 
 kp6_kp6_OBJ = $(patsubst lib-kp6-kp6/%,lib-kp6-kp6-p5/%,$(wildcard lib-kp6-kp6/KindaPerl6/Grammar/*.pm lib-kp6-kp6/KindaPerl6/Grammar.pm lib-kp6-kp6/KindaPerl6/Traverse.pm lib-kp6-kp6/KindaPerl6/Ast.pm lib-kp6-kp6/KindaPerl6/Visitor/*.pm lib-kp6-kp6/KindaPerl6/Runtime/Perl5/*.pm lib-kp6-kp6/KindaPerl6/Runtime/Perl6/*.pm lib-kp6-kp6/KindaPerl6/Test/*.pm ))
 
-all: $(kp6_mp6_OBJ) $(kp6_kp6_OBJ)
+all: $(kp6_mp6_OBJ) $(kp6_kp6_OBJ) kp6-kp6.pl
 
 lib-kp6-mp6-p5/KindaPerl6/Runtime/Perl6/%.pm: lib-kp6-mp6/KindaPerl6/Runtime/Perl6/%.pm
 	@echo COMPILE $< $@
@@ -25,12 +25,21 @@ lib-kp6-mp6-p5/KindaPerl6/Runtime/Perl5/%.pm: lib-kp6-mp6/KindaPerl6/Runtime/Per
 lib-kp6-kp6-p5/KindaPerl6/Runtime/Perl5/%.pm: lib-kp6-kp6/KindaPerl6/Runtime/Perl5/%.pm
 	cp $< $@
 
-
 lib-kp6-mp6-p5/%.pm: lib-kp6-mp6/%.pm
 	perl mp6.pl < $< > $@
 
 lib-kp6-kp6-p5/%.pm: lib-kp6-kp6/%.pm
 	perl kp6-mp6-perl5.pl < $< | perltidy > $@
+
+kp6-kp6.pl: kp6.p6
+	perl kp6-kp6-perl5.pl < $< | perltidy > temp.pl ; \
+		res=$$? ; \
+		if [ $$res = 0 -a -s temp.pm ] ; then \
+			cp temp.pm $@ ; \
+		else \
+			echo "*** Compilation failed with exit code: $$res!" ; \
+			exit; \
+		fi
 
 test: all
 	perl run_tests.pl
