[kp6] structural source layout changes finished.
git-svn-id: http://svn.pugscode.org/pugs@17630 c213334d-75ef-0310-aa23-eaa082d1ae64

diff --git a/v6/v6-KindaPerl6/Makefile b/v6/v6-KindaPerl6/Makefile
--- a/v6/v6-KindaPerl6/Makefile
+++ b/v6/v6-KindaPerl6/Makefile
@@ -1,10 +1,12 @@
-OBJ = $(patsubst lib/%,lib5/%,$(wildcard lib/KindaPerl6/Grammar/*.pm lib/KindaPerl6/Grammar.pm lib/KindaPerl6/Traverse.pm lib/KindaPerl6/Ast.pm lib/KindaPerl6/Visitor/*.pm lib/KindaPerl6/Runtime/Perl5/*.pm lib/KindaPerl6/Runtime/Perl6/*.pm lib/KindaPerl6/Test/*.pm ))
+kp6_mp6_OBJ = $(patsubst lib-kp6-mp6/%,lib-kp6-mp6-p5/%,$(wildcard lib-kp6-mp6/KindaPerl6/Grammar/*.pm lib-kp6-mp6/KindaPerl6/Grammar.pm lib-kp6-mp6/KindaPerl6/Traverse.pm lib-kp6-mp6/KindaPerl6/Ast.pm lib-kp6-mp6/KindaPerl6/Visitor/*.pm lib-kp6-mp6/KindaPerl6/Runtime/Perl5/*.pm lib-kp6-mp6/KindaPerl6/Runtime/Perl6/*.pm lib-kp6-mp6/KindaPerl6/Test/*.pm ))
 
-all: $(OBJ)
+kp6_kp6_OBJ = $(patsubst lib-kp6-kp6/%,lib-kp6-kp6-p5/%,$(wildcard lib-kp6-kp6/KindaPerl6/Grammar/*.pm lib-kp6-kp6/KindaPerl6/Grammar.pm lib-kp6-kp6/KindaPerl6/Traverse.pm lib-kp6-kp6/KindaPerl6/Ast.pm lib-kp6-kp6/KindaPerl6/Visitor/*.pm lib-kp6-kp6/KindaPerl6/Runtime/Perl5/*.pm lib-kp6-kp6/KindaPerl6/Runtime/Perl6/*.pm lib-kp6-kp6/KindaPerl6/Test/*.pm ))
 
-lib5/KindaPerl6/Runtime/Perl6/%.pm: lib/KindaPerl6/Runtime/Perl6/%.pm
+all: $(kp6_mp6_OBJ) $(kp6_kp6_OBJ)
+
+lib-kp6-mp6-p5/KindaPerl6/Runtime/Perl6/%.pm: lib-kp6-mp6/KindaPerl6/Runtime/Perl6/%.pm
 	@echo COMPILE $< $@
-	@perl kp6-perl5.pl < $< | perltidy > temp.pm ; \
+	@perl kp6-mp6-perl5.pl < $< | perltidy > temp.pm ; \
 		res=$$? ; \
 		if [ $$res = 0 -a -s temp.pm ] ; then \
 			cp temp.pm $@ ; \
@@ -12,10 +14,30 @@ lib5/KindaPerl6/Runtime/Perl6/%.pm: lib/KindaPerl6/Runtime/Perl6/%.pm
 			echo "*** Compilation failed with exit code: $$res!" ; \
 			exit; \
 		fi
-lib5/KindaPerl6/Runtime/Perl5/%.pm: lib/KindaPerl6/Runtime/Perl5/%.pm
+
+lib-kp6-kp6-p5/KindaPerl6/Runtime/Perl6/%.pm: lib-kp6-kp6/KindaPerl6/Runtime/Perl6/%.pm
+	@echo COMPILE $< $@
+	@echo kp6-kp6 is still compiled by kp6-mp6...
+	@perl kp6-mp6-perl5.pl < $< | perltidy > temp.pm ; \
+		res=$$? ; \
+		if [ $$res = 0 -a -s temp.pm ] ; then \
+			cp temp.pm $@ ; \
+		else \
+			echo "*** Compilation failed with exit code: $$res!" ; \
+			exit; \
+		fi
+
+
+lib-kp6-mp6-p5/KindaPerl6/Runtime/Perl5/%.pm: lib-kp6-mp6/KindaPerl6/Runtime/Perl5/%.pm
 	cp $< $@
-lib5/%.pm: lib/%.pm
+
+lib-kp6-kp6-p5/KindaPerl6/Runtime/Perl5/%.pm: lib-kp6-kp6/KindaPerl6/Runtime/Perl5/%.pm
+	cp $< $@
+
+
+lib-kp6-mp6-p5/%.pm: lib-kp6-mp6/%.pm
 	perl mp6.pl < $< > $@
+
 test: all
 	perl run_tests.pl
 
@@ -33,7 +55,8 @@ test_base: all
 
 forcerecompile:
 	echo "use -B instead"
-	find lib/KindaPerl6/ -name "*.pm"| grep -v \.svn |xargs touch
+	find lib-kp6-mp6/KindaPerl6/ -name "*.pm"| grep -v \.svn |xargs touch
+	find lib-kp6-kp6/KindaPerl6/ -name "*.pm"| grep -v \.svn |xargs touch
 
 clean: 
 	echo "make clean would destroy the compiler"
