[kp6] a simple Test.pm
git-svn-id: http://svn.pugscode.org/pugs@17725 c213334d-75ef-0310-aa23-eaa082d1ae64

diff --git a/v6/v6-KindaPerl6/Makefile b/v6/v6-KindaPerl6/Makefile
--- a/v6/v6-KindaPerl6/Makefile
+++ b/v6/v6-KindaPerl6/Makefile
@@ -2,9 +2,20 @@ kp6_mp6_OBJ = $(patsubst lib-kp6-mp6/%,lib-kp6-mp6-p5/%,$(wildcard lib-kp6-mp6/K
 
 kp6_kp6_OBJ = $(patsubst lib-kp6-kp6/%,lib-kp6-kp6-p5/%,$(wildcard lib-kp6-kp6/KindaPerl6/Grammar/*.pm lib-kp6-kp6/KindaPerl6/Grammar.pm lib-kp6-kp6/KindaPerl6/Traverse.pm lib-kp6-kp6/KindaPerl6/Ast.pm lib-kp6-kp6/KindaPerl6/Visitor/*.pm lib-kp6-kp6/KindaPerl6/Runtime/Perl5/*.pm lib-kp6-kp6/KindaPerl6/Runtime/Perl6/*.pm lib-kp6-kp6/KindaPerl6/Test/*.pm ))
 
-all: $(kp6_mp6_OBJ) $(kp6_kp6_OBJ)
+modules_OBJ = $(patsubst lib-modules/%,lib-modules-p5/%,$(wildcard lib-modules/GLOBAL/*))
+all: $(kp6_mp6_OBJ) $(kp6_kp6_OBJ) $(modules_OBJ)
 
 lib-kp6-mp6-p5/KindaPerl6/Runtime/Perl6/%.pm: lib-kp6-mp6/KindaPerl6/Runtime/Perl6/%.pm
+	@echo COMPILE $< $@
+	@perl kp6-mp6-perl5.pl < $< | perltidy > $@.temp ; \
+		res=$$? ; \
+		if [ $$res = 0 -a -s $@.temp ] ; then \
+			mv $@.temp $@ ; \
+		else \
+			echo "*** Compilation failed with exit code: $$res!" ; \
+			exit; \
+		fi
+lib-modules-p5/%.pm: lib-modules/%.pm
 	@echo COMPILE $< $@
 	@perl kp6-mp6-perl5.pl < $< | perltidy > $@.temp ; \
 		res=$$? ; \
